clang-tidy: delete default constructor
Default constructor was invalid for class semantics and caused
clang-tidy/Clang diagnostics. Mark the default constructor as
`=delete` to prevent accidental default construction and keep
-Werror builds green. No functional changes.

Fixed below errors
'''
../tools/io.hpp:54:19: error: explicitly defaulted move assignment operator is implicitly deleted [-Werror,-Wdefaulted-function-deleted]
   54 |     PpcMemDevice& operator=(PpcMemDevice&&) = default;
../bmc/skip_action.hpp:23:5: error: explicitly defaulted move constructor is implicitly deleted [-Werror,-Wdefaulted-function-deleted]
   23 |     SkipAction(SkipAction&&) = default;
../bmc/skip_action.hpp:24:17: error: explicitly defaulted move assignment operator is implicitly deleted [-Werror,-Wdefaulted-function-deleted]
   24 |     SkipAction& operator=(SkipAction&&) = default;  ^
../cleanup/cleanup.hpp:28:5: error: explicitly defaulted copy constructor is implicitly deleted [-Werror,-Wdefaulted-function-deleted]
   28 |     FileCleanupHandler(const FileCleanupHandler&) = default;
../cleanup/cleanup.hpp:29:25: error: explicitly defaulted copy assignment operator is implicitly deleted [-Werror,-Wdefaulted-function-deleted]
   29 |     FileCleanupHandler& operator=(const FileCleanupHandler&) = default;

'''

Change-Id: I1c154db8de65bfcde6b66e172562aabe16093647
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>