clang-tidy: silence unused parameter in constructor
Mark the constructor’s regionAddress parameter as intentionally unused
to satisfy -Wunused-parameter under -Werror. Use a no-op cast (void).
No functional behavior is altered.

Fixed below error
'''
../bmc/firmware-handler/lpc_aspeed.hpp:52:19: error: private field 'regionAddress' is not used [-Werror,-Wunused-private-field]
   52 |     std::uint32_t regionAddress;
'''

Change-Id: I52f4fef63d1e6809ac37cea7f822a5b9b6d28aa2
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>