Update patch set 1
Patch Set 1:

/home/jenkins-op/workspace/ci-repository/openbmc/phosphor-ipmi-blobs > git clone https://gerrit.openbmc-project.xyz/openbmc/phosphor-ipmi-blobs master ./ 
Traceback (most recent call last):
  File "/home/jenkins-op/workspace/ci-repository/openbmc/unit-test.py", line 1190, in <module>
    build_dep_tree(UNIT_TEST_PKG, CODE_SCAN_DIR, dep_added, dep_tree, BRANCH)
  File "/home/jenkins-op/workspace/ci-repository/openbmc/unit-test.py", line 342, in build_dep_tree
    dep_added = build_dep_tree(dep,
  File "/home/jenkins-op/workspace/ci-repository/openbmc/unit-test.py", line 342, in build_dep_tree
    dep_added = build_dep_tree(dep,
  File "/home/jenkins-op/workspace/ci-repository/openbmc/unit-test.py", line 330, in build_dep_tree
    for dep in set(pkg.build_system().dependencies()):
AttributeError: 'NoneType' object has no attribute 'dependencies'
Traceback (most recent call last):

Looks like something in the build scripts is broken -- when I ran this on my local CI (that hasn't been updated in a bit) it worked fine.

Patch-set: 1